### ISSUE TITLE
Error in sm_get

### ISSUE THREAD

**Issue by jeremyjaytaylor** [mattroumaya/surveymonkey#102]
As of last night, I am getting an "Error in sm_get(url = u, query = NULL, config = h, path = p) : 
  Forbidden (HTTP 403)" message when I try to do anything at all, including just pulling a list of surveys. It had been working flawlessly for months before last night. Any ideas what might be happening?

**Comment by mattroumaya** [comment]
When you run `getOption("sm_oauth_token")`, does it return your oauth token?

**Comment by jeremyjaytaylor** [comment]
But now that you mention that @mattroumaya, when I login to check my token on Surveymonkey's website it says my token is disabled. Any idea why that would be and how to re-enable?

**Comment by jeremyjaytaylor** [comment]
It appears it now says a higher level subscription is needed for API access than what I currently have. I currently have "Team Advantage" and apparently now "Team Premier" is needed. It must've changed because I've been using the API for months... Thanks for the idea that helped me find the answer, @mattroumaya. It's frustrating they changed features I was getting for my $$...

**Comment by mattroumaya** [comment]
@jeremyjaytaylor - this is interesting because I changed jobs somewhat recently, and have been able to pull responses with the API with an entirely free account. Is the app you created to access the API a public app? Or is it set to private? I think that might make a difference, but am also unsure of the downstream effects of public vs. private apps.

**Comment by jeremyjaytaylor** [comment]
It might be private. I'd be fine making it public as long as the data gathered with the app remains private. Do you know if that is the case?

**Comment by mattroumaya** [comment]
@jeremyjaytaylor sorry for the late response - did you get this sorted out? I would hesitate to recommend any API app settings where I'm not totally sure of the impact on data security, and would instead recommend reaching out to SurveyMonkey for guidance.

**Comment by Chhr1s** [comment]
I am having the same issue and am also using a free account and a private app. @jeremyjaytaylor, did you ever resolve this? Did you have to upgrade to a paid account? 

It's especially odd to me because I was successful less than 24 days ago (when this was filed). It stopped working without any changes.
